import type { RoleConfig } from "@/types";

export const ROLES: RoleConfig[] = [
  {
    role: "patient",
    label: "General Patient",
    emoji: "👤",
    description: "Everyday health management — track your health, consult doctors, order medicines and manage your family's health.",
    shortDesc: "Everyday health management",
    gradient: "from-[#1A6B3C] to-[#2EC4B6]",
    accentColor: "#2EC4B6",
    accentBg: "bg-teal-50",
    features: [
      "AarogyaBot — 24/7 AI Health Chatbot",
      "Symptom Checker & Diagnosis AI",
      "Health Score & History Dashboard",
      "Medicine Ordering & Reminders",
      "One-Tap SOS Emergency Alert",
    ],
    tags: ["AI Chatbot", "Health Score", "Medicine Order", "SOS"],
    authRoute: "/auth/patient",
  },
  {
    role: "rural",
    label: "Rural / Remote User",
    emoji: "🌾",
    description: "Low connectivity, local language support — offline features, nearby resources, and a voice AI assistant.",
    shortDesc: "Low connectivity, local language",
    gradient: "from-[#2D6A0A] to-[#8BC34A]",
    accentColor: "#8BC34A",
    accentBg: "bg-lime-50",
    features: [
      "Symptom Checker in 22 Languages",
      "Offline-First Doctor Consultation",
      "Voice-Based AI Assistant",
      "Nearest Hospital / Clinic Finder",
      "Direct 108 Ambulance Call",
    ],
    tags: ["22 Languages", "Offline", "Voice AI", "108 Call"],
    authRoute: "/auth/rural",
  },
  {
    role: "elderly",
    label: "Elderly Patient",
    emoji: "👵",
    description: "Assisted care with large text, voice mode, family monitoring, medicine reminders and fall detection.",
    shortDesc: "Assisted care & family monitoring",
    gradient: "from-[#BF360C] to-[#FF8A65]",
    accentColor: "#FF8A65",
    accentBg: "bg-orange-50",
    features: [
      "Medicine Reminder & Tracker",
      "Fall Detection Alerts to Family",
      "Daily Health Check-In",
      "Large Font / Voice UI Mode",
      "1-Tap Video Call with Family",
    ],
    tags: ["Large Font", "Fall Alert", "Family Monitor", "1-tap Call"],
    authRoute: "/auth/elderly",
  },
  {
    role: "women",
    label: "Women & Child Health",
    emoji: "👩",
    description: "Period tracking, pregnancy, breastfeeding, PCOS, child vaccination and growth — all in one place.",
    shortDesc: "Reproductive, maternal & child care",
    gradient: "from-[#880E4F] to-[#EC407A]",
    accentColor: "#EC407A",
    accentBg: "bg-pink-50",
    features: [
      "Period Tracker & Prediction",
      "PCOS/PCOD Awareness & Tracking",
      "Anonymous Gynec Chatbot",
      "Pregnancy Tracker",
      "Child Vaccination Scheduler",
    ],
    tags: ["Period Tracker", "Pregnancy", "PCOS", "Child Health"],
    authRoute: "/auth/women",
  },
  {
    role: "chronic",
    label: "Chronic Disease Patient",
    emoji: "💊",
    description: "Manage diabetes, BP, heart conditions — log vitals, sync wearables, and track medications daily.",
    shortDesc: "Diabetes, BP, heart & long-term",
    gradient: "from-[#4527A0] to-[#7E57C2]",
    accentColor: "#7E57C2",
    accentBg: "bg-violet-50",
    features: [
      "Glucose / BP Log with Graphs",
      "Medication Adherence Tracker",
      "Wearable Device Sync (Fitbit etc.)",
      "AI Health Risk Prediction",
      "Doctor Report Auto-Generation",
    ],
    tags: ["Glucose Log", "BP Tracker", "Wearable Sync", "AI Insights"],
    authRoute: "/auth/chronic",
  },
  {
    role: "mental",
    label: "Mental Health User",
    emoji: "🧠",
    description: "Anonymous AI therapist, mood journal, guided meditation, stress tests and peer support groups.",
    shortDesc: "Therapy, wellness & peer support",
    gradient: "from-[#0D47A1] to-[#42A5F5]",
    accentColor: "#42A5F5",
    accentBg: "bg-blue-50",
    features: [
      "Anonymous AI Therapist Chatbot",
      "Stress & Anxiety Test",
      "Mood Tracker & Journaling",
      "Guided Meditation & Breathing",
      "Anonymous Peer Support Chat",
    ],
    tags: ["Anonymous", "AI Therapist", "Meditation", "Peer Chat"],
    authRoute: "/auth/mental",
  },
  {
    role: "doctor",
    label: "Doctor / Clinician",
    emoji: "🩺",
    description: "Video consultations, digital prescriptions, patient records, AI scan reader and appointment management.",
    shortDesc: "Consultation, prescriptions & care",
    gradient: "from-[#004D40] to-[#26A69A]",
    accentColor: "#26A69A",
    accentBg: "bg-teal-50",
    features: [
      "Video Consultation (Live)",
      "Digital Prescription Generator",
      "Lab Report & AI Scan Reader",
      "Digital Patient Records",
      "Appointment Booking System",
    ],
    tags: ["Video Consult", "Prescriptions", "Patient Records", "AI Scans"],
    authRoute: "/auth/doctor",
  },
  {
    role: "hospital",
    label: "Hospital / Administrator",
    emoji: "🏨",
    description: "OPD queue, bed tracking, staff management, inventory, billing and analytics dashboard.",
    shortDesc: "Ops, inventory & analytics",
    gradient: "from-[#1A237E] to-[#5C6BC0]",
    accentColor: "#5C6BC0",
    accentBg: "bg-indigo-50",
    features: [
      "OPD Queue Management",
      "Hospital Bed / ICU Availability",
      "Staff Management System",
      "Inventory & Medicine Stock",
      "Analytics Dashboard",
    ],
    tags: ["OPD Queue", "Bed Tracker", "Analytics", "Billing"],
    authRoute: "/auth/hospital",
  },
];

export function getRoleConfig(role: string): RoleConfig | undefined {
  return ROLES.find((r) => r.role === role);
}
